# Generated by Django 4.2.8 on 2023-12-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
